select * from PULPIT;
select * from FACULTY;

select FACULTY.FACULTY, PULPIT_NAME from PULPIT
inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY
where PULPIT.FACULTY = 'FOF';

select * from AUDITORIUM;
select * from AUDITORIUM_TYPE;

select * from AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE = 'LH';


select * from PULPIT;

INSERT INTO PULPIT(PULPIT, PULPIT_NAME, FACULTY)
VALUES('HGG', 'HGG', 'TAEFFI');

DELETE FROM PULPIT 
WHERE PULPIT = 'HGG';

select * from SUBJECT;

INSERT INTO SUBJECT(SUBJECT, SUBJECT_NAME, PULPIT)
VALUES('HGG', 'HGG', 'CTOEPAMOEE');

DELETE FROM SUBJECT 
WHERE SUBJECT = 'HGG';

select * from AUDITORIUM_TYPE;

DELETE FROM AUDITORIUM_TYPE
where AUDITORIUM_TYPE = 'HGG';

select * from AUDITORIUM;

DELETE FROM AUDITORIUM
where AUDITORIUM = 'HGG';


/* --- PUT --- */
select * from FACULTY;

Select * from FACULTY where faculty = 'FOF';

select * from AUDITORIUM_TYPE where AUDITORIUM_TYPE = 'LH';

UPDATE AUDITORIUM_TYPE SET
AUDITORIUM_TYPENAME = @AUDITORIUM_TYPENAME
WHERE AUDITORIUM_TYPE = @AUDITORIUM_TYPE;

select * from AUDITORIUM;
